Implemented Price Calculation
REtangler/AltexSoft_DeliveryService pull request #1
Opened 2021-04-10 10:59 UTC by REtangler

2021-04-10 17:54 UTC, serhii-shkodenko requested changes
Задание практически выполнено. Исправь, пожалуйста, замечания. И перенеси все файлы проекта в отдельную папку, чтобы в дальнейшем не путаться, когда добавятся другие проекты.

2021-04-10 17:54 UTC, serhii-shkodenko commented on HomeWork.cs
> +            string subAddress = address.Substring(4);
Здесь ты исходишь из того, что адрес всегда будет содержать номер дома из трех цифр, однако это не так. Номер дома может состоять как из большего количества цифр, так и меньшего. В обоих случах логика определения адреса будет некорректной, и скидка может быть не насчитана. Эту логику определения адресов, отличающихся только номером дома, следует сделать более оптимальной.

2021-04-10 17:54 UTC, serhii-shkodenko commented on HomeWork.cs
> +        private void YoungDiscount(ref int discount, IEnumerable<int> infantsIds, IEnumerable<int> childrenIds, int iteration)
[Согласно конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members), имена методов в C# должны содержать глагол. Например, здесь будет уместным добавить глагол `Set`.

2021-04-10 17:54 UTC, serhii-shkodenko commented on HomeWork.cs
> +        private void NextStreetSameName(string address, ref int discount, string destination)
Согласно [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members), имена методов в C# должны содержать глагол.

2021-04-10 17:54 UTC, serhii-shkodenko commented on HomeWork.cs
> +        private void EURtoUSD(string currency, ref decimal price)
Согласно [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members), имена методов в C# должны содержать глагол. Возможно, здесь подойдет глагол `Convert`.

2021-04-10 17:54 UTC, serhii-shkodenko commented on HomeWork.cs
> +        private void StreetPrivilege(string address, ref decimal price)
Добавьте в имя метода глагол, чтобы следовать [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members) C#.

2021-04-10 18:19 UTC, serhii-shkodenko commented on HomeWork.cs
> +            decimal[] _prices = prices.ToArray();
Також варто врахувати, що локальні змінні у С# називаються у camelCase. Знак підкреслення `_` використувується лише на позначення полей класу.

2021-04-14 13:20 UTC, serhii-shkodenko requested changes
В целом почти все хорошо. Осталось поаравить эти замечания.

2021-04-14 13:20 UTC, serhii-shkodenko commented on CSharpModule/HomeWork.cs
> +            decimal[] pricesArray = prices.ToArray();
Используй неявное определение типа для переменной с помощью `var`.

2021-04-14 13:20 UTC, serhii-shkodenko commented on CSharpModule/HomeWork.cs
> +                pricesArray[i] *= (100 - discount) / 100m;
По условию задания, сначала нужно отнять от цены фиксированные скидки, а потом к оставшейся цене применить процентные скидки.

2021-04-14 20:15 UTC, REtangler commented on CSharpModule/HomeWork.cs
> +                pricesArray[i] *= (100 - discount) / 100m;
Я практично впевнений, що у мене так само виконана послідовність як і у Вашому рішенні. Перегляньте будь ласка ще раз.

2021-04-15 20:51 UTC, serhii-shkodenko commented on CSharpModule/HomeWork.cs
> +                pricesArray[i] *= (100 - discount) / 100m;
Дійсно, все ок.

2021-04-15 20:52 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-04-15 21:44 UTC, merged