Implemented functionality for Program.cs
REtangler/AltexSoft_DeliveryService pull request #3
Opened 2021-04-20 19:26 UTC by REtangler

Implemented methods for b2b and b2c logic
Businesses can add PC parts and peripherals, view added items and active clients' orders
Clients can add items to their order and view it

2021-04-27 02:17 UTC, serhii-shkodenko requested changes

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +    class Controller : IControllable
Не хватает модификатора доступа.

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            _pcParts = storage.PcParts.ToList();
`ToList()` здесь вызывать излишне. `PcParts` и так свойство, возвращающее `IList<T>`.

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            _pcPeripherals = storage.PcPeripherals.ToList();
`ToList()` здесь вызывать излишне. `PcPeripherals` и так свойство, возвращающее `IList<T>`.

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            _orders = storage.Orders.ToList();
`ToList()` здесь вызывать излишне. `Orders` и так свойство, возвращающее `IList<T>`.

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +        public Storage Start(Storage storage)
Нарушен Dependency inversion principle. Используй интерфейсы.

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +        private static List<PcPart> _pcParts;
Тебе эти переменные не нужны. Достаточно сохранить в `private readonly` поле объект `IStorage` из конструктора.

2021-04-27 02:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Presenter.cs
> +    class Presenter : IPresentable
Не хватает модификатора доступа.

2021-05-04 13:06 UTC, serhii-shkodenko approved these changes
Смешана логика работы с интерфейсом пользователя и для работы с бизнес-объектами. Это нужно разделить. При этом код выглядит чисто, что очень хорошо.

2021-05-04 13:06 UTC, serhii-shkodenko commented on DeliveryService/UI/Dialogues.cs
> +            var presenter = new Presenter();
Этот код повторяется несколько раз, значит нужно было делать соответствующую инъекцию в конструктор. Учти, что это класс `Presenter` должен содержать диалоги, а не наоборот.

2021-05-04 13:06 UTC, serhii-shkodenko commented on DeliveryService/UI/ItemsController.cs
> +    public class ItemsController : IItemsController
Этот класс содержаит как бизнес логику, так и осуществляет вывод на консоль. Это нарушение Single responsibility principle. 

1. Работу с интерфейсом нужно выделить либо в классы-диалоги, либо в класс `Presenter`.  
2. Здесь в конструктор сделать инъекцию хранилища и через методы этого класса вносить изменения в данные, храняющиеся в этом хранилище.

2021-05-04 13:08 UTC, serhii-shkodenko requested changes
Смешана логика работы с интерфейсом пользователя и для работы с бизнес-объектами. Это нужно разделить. При этом код выглядит чисто, что очень хорошо. Конкретные рекомендации указаны выше.

2021-05-06 00:05 UTC, REtangler commented on DeliveryService/UI/Controller.cs
> +            var presenter = new Presenter();
Не впевнений чи виконав цю правку, тому що об'єднав презентер і діалоги в один клас за однією з пропозицій.
Не до кінця зрозумів як і навіщо в такому випадку повинен існувати Dialogue.cs

2021-05-06 00:07 UTC, REtangler commented on DeliveryService/Logic/RegExpression.cs
> +﻿using System.Text.RegularExpressions;
Трохи заплутався з гілками і тому тут є клас з наступного завдання.

2021-05-06 00:08 UTC, REtangler commented on DeliveryService/Interfaces/IRegEx.cs
> +﻿namespace DeliveryService.Interfaces
Трохи заплутався з гілками і тому тут є клас з наступного завдання.

2021-05-06 00:09 UTC, REtangler commented on DeliveryService/UI/Presenter.cs
> +        private readonly RegExpression _regExpression;
Трохи заплутався з гілками і тому тут є клас з наступного завдання.

2021-05-11 20:01 UTC, serhii-shkodenko requested changes
Треба дорозділити шар інтерфейсу від бізнес логіки. У коментах про це є. Якщо незрозуміло, питай.

2021-05-14 23:19 UTC, serhii-shkodenko requested changes
Загалом все добре. Виправ, будь ласка, ці зауваження і буде апррув для цього ПР.

2021-05-14 23:19 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            switch (choice)
Цей метод виконує певні операції в залежності від того, що зробив користувач у твоєму консольному UI. Це означає, що цей метод не можна використати в іншому додатку, наприклад із графічним інтерфейсом, тобто ламає переносимість коду. Шар бізнес логіки не має залежати від особливостей реалізації UI.

Оптимальним тут буде розділити цей метод на два різних і визивати вже тільки певну частину. Це дозволить прибрати приведення типів (касти).

2021-05-14 23:19 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            switch (choice)
Цей метод виконує певні операції в залежності від того, що зробив користувач у твоєму консольному UI. Це означає, що цей метод не можна використати в іншому додатку, наприклад із графічним інтерфейсом, тобто ламає переносимість коду. Шар бізнес логіки не має залежати від особливостей реалізації UI.

Оптимальним тут буде розділити цей метод на два різних і визивати вже тільки певну частину. Це дозволить прибрати приведення типів (касти).

2021-05-14 23:19 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +                    pcPart.Id = _storage.PcParts.Count;
Тут некоректна логіки отримання `Id`. Розглянь такий сценарій:

Вихідна колекція:
```
PcPart {  Id = 1 };
PcPart {  Id = 2 };
PcPart {  Id = 3 };
```

Видалимо останній елемент. Буде:
Вихідна колекція:
```
PcPart {  Id = 1 };
PcPart {  Id = 2 };
```

Додамо новий елемент із застосуванням поточної логіки:
```
PcPart {  Id = 1 };
PcPart {  Id = 2 };
PcPart {  Id = 2 };
```

Сценарій для логіки `_storage.PcParts.Count + 1`.
Вихідна колекція:
```
PcPart {  Id = 1 };
PcPart {  Id = 2 };
PcPart {  Id = 3 };
```

Видалимо середній елемент. Буде:
Вихідна колекція:
```
PcPart {  Id = 1 };
PcPart {  Id = 3 };
```

Додамо новий елемент із застосуванням поточної логіки:
```
PcPart {  Id = 1 };
PcPart {  Id = 3 };
PcPart {  Id = 3 };
```

Для того щоб коректно вирахувати новий `Id`, почитай про метод розширення `Max()` з `System.Linq`.

2021-05-14 23:19 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +                    pcPeripheral.Id = _storage.PcPeripherals.Count;
Некоректна логіка обчислення нового `Id`, дивись вище.

2021-05-14 23:19 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +        public IStorable GetStorage()
Я не знайшов, де ти використовуєш цей метод. Його можна видалити. Не забудь прибрати його і з інтерфейсу також.

2021-05-15 02:19 UTC, REtangler commented on DeliveryService/UI/Controller.cs
> +        public IStorable GetStorage()
я його використовую в конструкторі презентера, для того щоб я міг виводити, наприклад, список замовлень або предметів на продажі.

2021-05-18 16:04 UTC, serhii-shkodenko requested changes
Прояснилось із тим методом. Я написав свої зауваження, поправ, будь-ласка, код і ПР отримає аппрув.

2021-05-18 16:04 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +        public IStorable GetStorage()
Ага, я знайшов місце. Коли шукав минулого разу не розгорнув усі файли. 

Так, я зрозумів для чого ти його використовуєш. Ти надаєш коду, що визиває цей метод, доступ до залежності. Да, він тільки на читання, проте це все одно доступ. 

Твою реалізацію я б назвав протіканням шарів, або протіканням абстракцій. Тобто будь-який рівень, який знає про шар бізнес логіки (контролер), буде знати і про шар із даними (сторедж). Так робити - зась. Тому я прошу тебе переробити цей момент наступним чином:

1. Прибрати цей метод. 
2. Створити методи, які будуть доступні для визову, що будуть використовувати залежність `IStorable`. У цих методах має бути те, що ти робив у шарі інтерфейсу (клас `Presenter`), проте не все, а лише те, що робилось на рівні бізнес логіки. Робота з інтерфейсом, валідація тощо мають зашалитися у класі `Presenter`. 
3. У класі `Presenter` визивати новостворені методи. 
4. Прибрати у класу `Presenter` залежність `IStorable`.

2021-05-18 22:13 UTC, serhii-shkodenko requested changes
Ти реалізував мої попередні рекоментації, але не зауважив про розділення методів на частини, що відповідають за роботу із бізнес логікою, і шо працюють із інтерфейсом. Детальніше я розписав у коментарях. Поправ, будь ласка.

2021-05-18 22:13 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            var sb = new StringBuilder();
Цей метод готує рядок для відображення на консолі. Це явно відповідальність класу або шару, що відповідає за інтерфейс користувача. А цей клас має реалізовувати лише бізнес логіку, тобто він має отримувати дані і на основі бізнес правил їх обробляти. 

Цей метод називається `ShowActiveOrders`. Краще його переназвати хоча б на `GetActiveOrders`. Я так бачу, що він має, використовуючи залежність, отримати замовлення і вибрати лише активні з них і повернути їх тому об'єкту, що буде визивати цей метод. А уже цей обєкт, отримавши, або не отримавши цей список замовлень, створити рядок для його відображення. 

Тобто цей метод треба переназвати і розділити його на дві частини. Частину, що працює із бізнес логікою, залишити у цьому методі і цьому класі. А частину, що генерує рядок, винести в класс `Presenter`.

2021-05-18 22:13 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +        public string ShowPcPeripherals()
Тут також краще розділити цей метод. Див коментар вище.

2021-05-18 22:13 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +        public string ShowPcParts()
Тут також краще розділити цей метод. Див коментар вище.

2021-05-18 22:13 UTC, serhii-shkodenko commented on DeliveryService/Interfaces/IItemPresentable.cs
>      public interface IItemPresentable
Цей інтерфейс краще видалити і його методи винести в `IPresentable`.

2021-05-19 10:05 UTC, REtangler commented
Прибрав частини з методів контролера і вони тепер повертають переліки з сховища, але хіба це не практично те саме, що в мене було з методом `GetStorage()` ? Не розумію чи в цьому випадку я зробив гірше, повернувшись на кілька кроків назад, чи так і має бути.

2021-05-19 10:25 UTC, serhii-shkodenko commented
> Прибрав частини з методів контролера і вони тепер повертають переліки з сховища, але хіба це не практично те саме, що в мене було з методом `GetStorage()` ? Не розумію чи в цьому випадку я зробив гірше, повернувшись на кілька кроків назад, чи так і має бути.

Ні, ти все зробив, як я запропонував. Реалізація із `GetStorage()` була протіканням шарів: твій шар із користувацьким інтерфейсом знав про "базу", так не має бути. Загалом "спілкування" шарів має відбуватися по такій схемі:

1. Інтерфейс отримує запит від користувача і звертається до шару із бізнес логікою: користувач хоче отримати переглянути 10 товарів, дай мені їз будь ласка. 
2. Бізнес шар отримує запит і розуміє, що у неього немає даних. Він звертається до бази даних, і просить її надати дані для роботи 10 товарів, їх категорії, і таке інше. 
3. База даних отримує запит, обробляє його і повертає ці 10 товарів, якщо вони є.
4. Шар із бізнес логікою отримує дані і на основі бізнес правил, тобто різних опцій, як, наприклад, мають групуватися ці товари, чи можливо їх навіть показата для саме цього користувача і так інше повертає інтерфейсу ці бізнес об'єкти.
5. Шар інтерфейсу отримує ці бізнес об'єкти і вже показує їх користувачу.

2021-05-19 10:26 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-05-19 13:39 UTC, merged