April 28
REtangler/AltexSoft_DeliveryService pull request #4
Opened 2021-04-30 01:24 UTC by REtangler

2021-05-06 00:12 UTC, REtangler commented
Переплутав гілки і запушив не туди.

2021-05-11 20:11 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpression.cs
> +    public class RegExpression : IRegEx
Назва цього класу не дає уявлення про його призначення. Пропоную використати ці іменники в назвах: `Validator`, `Checker`.

2021-05-11 20:15 UTC, serhii-shkodenko commented on DeliveryService/UI/Dialogues.cs
> +            var regex = new RegExpression();
Ти створив інтерфейс для класу `RegExpression`, тому це можна використати для ін'єкції в конструктор класу `Dialogues`. А тут ти цього не використовуєш.

2021-05-11 20:17 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpression.cs
> +            var patterns = new[]
Цю змінну має смисл переписати у вигляді приватного статичного поля. Тоді не буте потреби кожного разу її ініціалізовувати кожного разу, як визивається метод `CheckNumber`.

2021-05-11 20:54 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpression.cs
> +            var patterns = new[]
Цю змінну має смисл переписати у вигляді приватного статичного поля. Тоді не буте потреби кожного разу її ініціалізовувати кожного разу, як визивається метод `CheckAddress`.

2021-05-11 20:55 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpression.cs
> +                @"(улица)\s[А-Я][а-я]+\,\s(д)\.\s\d+\,\s(кв)\.\s\d+",
Ці патерни можна скоротити до одного.

2021-05-11 20:56 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpression.cs
> +                @"\+\d{3}\(\d{2}\)\d{3}\s\d{2}\s\d{2}",
Ці паттерни можна скоротити до одного.

2021-06-03 20:52 UTC, serhii-shkodenko requested changes

2021-06-03 20:52 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpressionValidator.cs
> +    public class RegExpressionValidator : IRegEx
Насправді, механізм валідації, у даному випадку регулярні вирази, є деталлю реалізації, тому цих слів не має бути у назвах класів, методів і інтерфейсів. Достатньо слова `Validato`r та / або його комбінацій з іншими словами.

2021-06-03 20:52 UTC, serhii-shkodenko commented on DeliveryService/Logic/RegExpressionValidator.cs
> +        private static readonly string NumberPattern = @"(\+38)?0\(?\d{2}\)?\s?\d{3}\s?\d{2}\s?\d{2}\b";
Все ж таки варто додати, що номер телефону, а не просто якийсь номер.

2021-06-03 21:09 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-06-03 21:09 UTC, merged