May 12 logger
REtangler/AltexSoft_DeliveryService pull request #5
Opened 2021-05-15 01:12 UTC by REtangler

2021-05-22 21:12 UTC, REtangler commented
Логгер в мене використовуться в класі `Presenter.cs`, чи було би краще використовувати його зразу в шарі з бізнес логікою (`Controller.cs`)?

2021-06-03 21:01 UTC, serhii-shkodenko requested changes

2021-06-03 21:42 UTC, serhii-shkodenko requested changes

2021-06-03 21:42 UTC, serhii-shkodenko commented on DeliveryService/Logic/Logger.cs
> +            streamWriter.WriteLine($"Log Entry: {DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}");
Я думаю замість трьох операцій запису, краще здійснити одну. Тому сформуй рядок для запису і одни раз виклич `streamWriter.WriteLine()`.

2021-06-03 21:49 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-06-03 21:52 UTC, merged