Implemented Serialization and Deserialization
REtangler/AltexSoft_DeliveryService pull request #6
Opened 2021-05-24 01:04 UTC by REtangler

2021-05-29 22:48 UTC, serhii-shkodenko requested changes

2021-05-29 22:48 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
> +            _serializer.SerializeAndSave(_storage);
Я бы не делал метод-обертку над `SerializeAndSave()`. Используй сразу `_serializer.SerializeAndSave(_storage)` где нужно.

2021-05-29 22:48 UTC, serhii-shkodenko commented on DeliveryService/Utils/Serializer.cs
> +    class Serializer : ISerializable
Модификатор доступа забыл.

2021-06-03 22:09 UTC, serhii-shkodenko requested changes

2021-06-03 22:09 UTC, serhii-shkodenko commented on DeliveryService/Utils/RegExpression.cs
> +    public class RegExpression : IRegEx
Я так розумію цей клас можна видалити разом із інтерфейсом, бо раніше ти їх перейменував. Перевір будь ласка, і видали, якщо валідатор на місці.

2021-06-03 22:16 UTC, REtangler commented on DeliveryService/Utils/RegExpression.cs
> +    public class RegExpression : IRegEx
чомусь була запушена застаріла версія, оновив до поточної

2021-06-11 16:02 UTC, serhii-shkodenko requested changes
Поправ, будь ласка, ці невеличкі зауваження і будет апрув.

2021-06-11 16:02 UTC, serhii-shkodenko commented on DeliveryService/Utils/Serializer.cs
> +            FilePath = AppDomain.CurrentDomain.BaseDirectory + "/" + FileName;
`AppDomain.CurrentDomain.BaseDirectory` вже поввертає шлях зі слешем/зворотнім слешем на кінці (в залежності від операційно системи). Тому треба прибрати `"/"` зі шляху.

Символ, що розділяє шлях, є різним на різних ОС. Тому, якщо доведеться його використовувати краще затосовувати `Path.PathSeparator`.

2021-06-11 16:02 UTC, serhii-shkodenko commented on DeliveryService/Utils/Serializer.cs
> +        public string FilePath { get; init; }
`init` тут краще прибрати і залишити лише геттер.

2021-06-11 16:02 UTC, serhii-shkodenko commented on DeliveryService/Utils/Serializer.cs
> +        public string FileName { get; init; }
`init` тут краще прибрати і залишити лише геттер.

2021-06-11 17:26 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-06-11 17:27 UTC, merged