May 26 caching
REtangler/AltexSoft_DeliveryService pull request #7
Opened 2021-05-29 22:03 UTC by REtangler

Used delegate to output text in debug window.
Cached individual items invalidate after 2 minutes.
Max items stored in cache are limited to 2 lists.

2021-05-29 22:43 UTC, serhii-shkodenko requested changes

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _currentList.Add(list);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _currentList.RemoveAt(0);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _currentList.RemoveAt(ind);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _timings.RemoveAt(ind);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _currentList.Add(list);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _timings.RemoveAt(0);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                _timings.Add(DateTime.Now);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-05-29 22:43 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +            var ind = _currentList.IndexOf(tempList);
Твоя реализация не потокобезопасна. Попробуй примерить `lock` или `Monitor()`.

2021-06-12 15:26 UTC, serhii-shkodenko requested changes
Поправ, будь ласка, невеличке зауваження і буде апрув.

2021-06-12 19:29 UTC, REtangler commented on DeliveryService/Data/Cache.cs
> +        private static readonly object Lock = new object();
ReSharper мені підказував писати це поле в паскалі, коли воно є статичним. Якщо це поле було б не статичним то я його писав би `_lock`
Також судячи з [цієї статті](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions?redirectedfrom=MSDN) публічні поля варто записувати паскалем, те що в мене воно є приватним скасовує це правило?
Дуже багато розбіжностей як на stackoverflow так і на різних форумах на рахунок цієї теми, не підкажете на які ресурси варто опиратись якщо з'являються такі розбіжності?

Отже, все-таки змінити найменування поля чи залишити як є?

2021-06-14 13:50 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +        private static readonly object Lock = new object();
Я подивився висхідний код .NET і там немаєк консистентності у цьому питанні. Тому поки залиш так. як є.

2021-06-14 14:04 UTC, serhii-shkodenko requested changes
Знайшо, що ще можна поліпшити.

2021-06-14 14:04 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +        public void AddList<T>(IList<T> list, Action<string> debugHandler)
Тут також варто прибрати `List` із імені.

2021-06-14 14:04 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                if (_currentList.Count < 2)
В завданні сказано про 5 обє'ктів у кеші. Виходить, що в тебе кешується лише один об'єкт в принципі, незалежно від `T`.

2021-06-14 15:13 UTC, REtangler commented on DeliveryService/Data/Cache.cs
> +                if (_currentList.Count < 2)
Тупа помилка, мав на увазі: `if (_currentList.Count <= 2)`

2021-06-14 18:09 UTC, REtangler commented on DeliveryService/Data/Cache.cs
> +                var tempList = (IList<T>)_currentList.SingleOrDefault(x => typeof(List<T>) == x.GetType());
Але ж в такому випадку я буду нехтувати рештою коду, я тут повертаю `null` тільки коли не було знайдено потрібного об'єкта. А якщо необхідний об'єкт було знайдено то я йду далі, проводжу певні операції та повертаю знайдений об'єкт.

2021-07-10 22:33 UTC, serhii-shkodenko requested changes

2021-07-10 22:33 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                if (_cachedObjects.Count <= 2)
Вище ти створюєш колекції з двох елементів. Якщо ти залишиш тут перевірку на дорівнює, то після додавання у колекціяї буде три елементи. Код буде працювати, прото якщо твій намір зберігати виклично два елементи, то "=" краще прибрати.

2021-07-10 22:33 UTC, serhii-shkodenko commented on DeliveryService/UI/Controller.cs
>      {
Цей класс  не чинить ніяких дій із UI, проте чомусь знаходиться у цьому неймспейсі. Краще винести його в інше місце. Краще до неймспейсу, повязаного із бізнес логікою, незважачи на те що у класі багато методів, які б краще було розмістити в класі-репозиторії. Але цей патерн ви будете вивчати під час наступного модуля.

2021-07-10 22:34 UTC, serhii-shkodenko commented on DeliveryService/Data/Cache.cs
> +                var tempList = (IList<T>)_currentList.SingleOrDefault(x => typeof(List<T>) == x.GetType());
Дійсно, випало з уваги, що там далі ти перевіряєш час створення ще.

2021-08-09 06:12 UTC, serhii-shkodenko requested changes
Виглядає добре, можна мержити.

2021-08-09 06:12 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-08-09 15:05 UTC, merged