June 4 Currency Exchange from an API
REtangler/AltexSoft_DeliveryService pull request #8
Opened 2021-06-08 23:00 UTC by REtangler

Implemented secondary currency output from an external API

2021-06-14 14:17 UTC, serhii-shkodenko requested changes

2021-06-14 14:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Presenter.cs
> +        public Presenter(Controller controller, IValidator regExp, ILogger logger, IExchangeable exchanger)
Я думаю, що залежність має бути у бізнес шарі. Тут ти маєш лише показати користувачу результат корвертації.

2021-06-14 14:17 UTC, serhii-shkodenko commented on DeliveryService/UI/Presenter.cs
> +            var currencies = _exchanger.GetAllCurrencies().Result;
Це блокуюче очікування. Так робити не можна. Використовуй `await`.

2021-06-14 14:17 UTC, serhii-shkodenko commented on DeliveryService/Utils/CurrencyExchanger.cs
> +        private string ConvertFrom { get; init; }
Раз ти ініціюєш це поле у конструкторі, сеттер можна взагалі прибрати.

2021-06-14 14:17 UTC, serhii-shkodenko commented on DeliveryService/Utils/CurrencyExchanger.cs
> +            var exchangeRate = DeserializeResponseAsync(response.Result).Result;
Це блокуюче очікування, не роби так.

2021-06-14 14:17 UTC, serhii-shkodenko commented on DeliveryService/Utils/CurrencyExchanger.cs
> +            using (var streamReader = new StreamReader(responseStream))
Використовуй новий синтаксис для `using`.

2021-07-11 14:34 UTC, serhii-shkodenko requested changes

2021-07-11 14:34 UTC, serhii-shkodenko commented on DeliveryService/Utils/CurrencyExchanger.cs
> +    public class CurrencyExchanger : IExchangeable
Цей клас відповідає як за отримання даних, так із за їх інтерпритацію (конвертацію валют). Це порушує Single responsibility principle. Конвертацію валют можна цілком покласти на класи із бізнес рівня, а тут залишити лише отримання даних, і тоді перейменувати клас.

2021-08-21 18:56 UTC, serhii-shkodenko requested changes
Поправ, будь ласка, ці невеличкі зауваження і буде апрув. Круто, що знайшов норм API для курсів валют. І ще одне, ключі доступу ніколи не додавай у висхідний код. Вони мають бути повністю секретними. У 4-ому модулі ви маєте це проходити, тому я не зауважував це як зауваження.

2021-08-21 18:56 UTC, serhii-shkodenko commented on DeliveryService/Interfaces/ICurrencyRetriever.cs
> +        Task<decimal> DeserializeResponseAsync(Stream responseStream);
Зазвичай операція отримання якихось даних з віддаленого API передбачає отимання вже десеріалізованих даннх, тобто якогось об'єкта. Тому окремий метод для отримання Stream'у зазавичай не роблять. Операціяю отриманя даних і їх деcеріалізацію можна сміливо об'єднувати в один метод. Якщо ж бізнес логіка будет потребувати роботу із сирими даними, то для цього я бачив реалізацію ріжноманітних інтерсепторів або колбеків.

2021-08-21 18:56 UTC, serhii-shkodenko commented on DeliveryService/Interfaces/ICurrencyRetriever.cs
> +        string ConvertTo { get; set; }
Я б не зберігав валюту, в яку треба конверутваи ціну, а кожного разу передавав її у метод конверації. Твій сервіс може використоуватися у різних місцях і це значення може бути кожного разу різним.

2021-08-21 18:56 UTC, serhii-shkodenko commented on DeliveryService/UI/Presenter.cs
> +                Console.WriteLine("Choose your preferred currency:");
Наскільки я зрозумів, мається на уважі валюта конвертації, я б так і написав (бо ціна отримуєтья у гривнях, а потім конвертується у бажану).

2021-08-21 18:56 UTC, serhii-shkodenko commented on DeliveryService/UI/Presenter.cs
> +                    Console.WriteLine("Choose a currency!");
Наскільки я зрозумів, мається на уважі валюта конвертації, я б так і написав (бо ціна отримуєтья у гривнях, а потім конвертується у бажану).

2021-08-21 18:56 UTC, serhii-shkodenko commented on DeliveryService/Utils/Controller.cs
> +        public async Task<decimal> ExchangeCurrency(decimal money, string convertTo)
Ім'я методу трохи незрозуміле. З цього імені виходить, що можна конвертувати будь-яку валюту у будь-яку валюту, а це не так, тільки гривні у будь-яку валюту.

2021-08-21 19:58 UTC, REtangler commented
Дякую за зауваження на рахунок секретних ключів, такі речі варто запам'ятати)
Тут я вирішив залишити його, щоб можна було перевірити правильність роботи завдання без створення власних акаунтів на різних сервісах.

2021-08-21 20:01 UTC, serhii-shkodenko requested changes
Поправ цю назву, будь ласка, і буде апрув.

2021-08-21 20:01 UTC, serhii-shkodenko commented on DeliveryService/Interfaces/ICurrencyRetriever.cs
> +        Task<decimal> DeserializeResponseAsync(string convertTo);
Краще залишити назву GetExchangeRatesAsync(). Сорі, я міг тебе законф'юзити, бо не на тому рядку поставив коментар.

2021-08-21 20:02 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-08-21 20:03 UTC, merged